// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: Default
///   FirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqXEGFSSNsiQwuQ70_J6YeWxRbn8DnIsQ',
    appId: '1:330629038977:web:85972d83745879bf3f1e80',
    messagingSenderId: '330629038977',
    projectId: 'islamic-app-324b7',
    authDomain: 'islamic-app-324b7.firebaseapp.com',
    storageBucket: 'islamic-app-324b7.firebasestorage.app',
    measurementId: 'G-B5GKTJTR9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ki9VTgCdXxwbmaLMXRWmkgz5Q5EiOSo',
    appId: '1:330629038977:android:81aa044c622b10053f1e80',
    messagingSenderId: '330629038977',
    projectId: 'islamic-app-324b7',
    storageBucket: 'islamic-app-324b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANjcj_Lc_TuHoB3_WqZ9eT-V3jdq10q8w',
    appId: '1:330629038977:ios:d89adb6aad41814b3f1e80',
    messagingSenderId: '330629038977',
    projectId: 'islamic-app-324b7',
    storageBucket: 'islamic-app-324b7.firebasestorage.app',
    androidClientId: '330629038977-v112nukflel704hpa99to4u2ta71g2a3.apps.googleusercontent.com',
    iosClientId: '330629038977-ms33q46mdqfkbo71mf7gnd8gm8vkb83q.apps.googleusercontent.com',
    iosBundleId: 'com.example.islamicApp',
  );

}